### PR TITLE
[SRVKS-281] Explicitly call out resources to manage.

### PR DESCRIPTION
**Pull request by markusthoemmes**
See https://issues.redhat.com/browse/SRVKS-281 for reference.

**Release Note**

```release-note
NONE
```

/assign @jcrossley3

### CODE REVIEW

**Review by jcrossley3 — COMMENTED** [review]
Have we tried this upstream and it was rejected? Seems like non-RedHatters would be interested in this, too, right?

**Comment by matzew** [comment]
In eventing they always like that kind of contribution :-)

**Comment by markusthoemmes** [comment]
It doesn't make sense to upstream it at this point anymore. We usually upstream stuff immediately, but as upstream has already changed the operator group, there's no reason to have it in there at this point as it just creates unnecessary room for error upstream.

Once we drop the old operator group, we can ditch this as well.

**Comment by matzew** [comment]
seems reasonable 

/lgtm

**Comment by matzew** [comment]
/hold 

looks like we do not really need this ... ?

**Comment by markusthoemmes** [comment]
/hold cancel

We'll most likely have the old CRD in place.

**Pull request merged**
